import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/page";
import { Toaster } from "react-hot-toast";

// Font konfigurasi
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Pilih weight sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Management Articles | By Rahmet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {/* <Navbar /> */}
        {/* <div className="py-16"> */}
        {children}
        <Toaster position="top-center"/>
        {/* </div> */}
      </body>
    </html>
  );
}
